name: fastingcalender
description: "Fasting Calendar is a simple and convenient way to view the fasting days of the Orthodox Christian liturgical year."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  table_calendar: ^3.0.9
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
